#ifndef __CATHPKT_IOCTL_H
#define __CATHPKT_IOCTL_H

#define CATHPKT_IOC_MAGIC 0xEE
#define CATHPKT_IOCTL_ENALBE_WRITE       _IOWR(CATHPKT_IOC_MAGIC, 0, CATHPKT_IOCTL_PARMS)
#define CATHPKT_IOCTL_HOST_INFO_READ     _IOWR(CATHPKT_IOC_MAGIC, 1, CATHPKT_IOCTL_PARMS)

#endif //__EVENT_H
